dist: bionic
language: cpp
os: linux
before_install:
  - .travis/preinstall.sh
compiler:
  - gcc
  - clang
env:
  - CMAKE_OPTS=-DBUILD_ROCKSDB_STORAGE=FALSE -DCMAKE_BUILD_TYPE=DEBUG
  - CMAKE_OPTS=-DBUILD_ROCKSDB_STORAGE=FALSE -DCMAKE_BUILD_TYPE=RELEASE
script:
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake $CMAKE_OPTS .. && make -j $(getconf _NPROCESSORS_ONLN) && ctest
