


/***************************************
 Autogenerated by cmfc. Do not modify.
***************************************/

# include <cstdint>
# include <map>
# include <string>
# include <utility>
# include <variant>
# include <vector>

# include "serialize.h"

namespace concord::messages {

struct TestIntegral {
  static constexpr uint32_t id = 1; 

  uint16_t f1; 
  bool f2; 
  uint32_t f3; 
  int64_t f4; 
};

std::vector<uint8_t> Serialize(const TestIntegral& t) {
  std::vector<uint8_t> output;
  cmf::Serialize(output, t.f1);
  cmf::Serialize(output, t.f2);
  cmf::Serialize(output, t.f3);
  cmf::Serialize(output, t.f4);
  return output;
}

void Deserialize(const std::vector<uint8_t>& input, TestIntegral& t) {
  auto it = input.begin();
  cmf::Deserialize(it, t.f1);
  cmf::Deserialize(it, t.f2);
  cmf::Deserialize(it, t.f3);
  cmf::Deserialize(it, t.f4);
}

} // namespace concord::messages
